//
//  LegalityCheckStrings.swift
//  PKHeXMac
//
//  Created by Matthew Conrad on 3/18/24.
//

import Foundation

enum LegalityCheckStrings {
    // Message String Name format: L/F[Category][Summary]
    /* General Strings */

    /// Default text for indicating validity.
    static var valid = "Valid."

    /// Default text for indicating legality.
    static var legal = "Legal!"

    /// Default text for indicating an error has occurred.
    static var error = "Internal error."

    /// Analysis not available for the `PKM`
    static var analysisUnavailable = "Analysis not available for this Pokémon."

    /// Format text for exporting a legality check result.
    static var format0_1 = "{0}: {1}"

    /// Format text for exporting a legality check result for a Move.
    static var formatMove = "{0} Move {1}: {2}"

    /// Format text for exporting a legality check result for a Relearn Move.
    static var formatRelearnMove = "{0} Relearn Move {1}: {2}"

    /// Format text for exporting the type of Encounter that was matched for the `PKM`
    static var formatEncounterType = "Encounter Type: {0}"

    /// Format text for exporting the `PIDIV.OriginSeed` that was matched for the `PKM`
    static var formatOriginSeed = "Origin Seed: {0}"

    /// Format text for exporting the `PIDIV.Type` that was matched for the `PKM`
    static var formatPIDType = "PID Type: {0}"

    /// Severity string for `Severity.Invalid`
    static var severityInvalid = "Invalid"

    /// Severity string for `Severity.Fishy`
    static var severityFishy = "Fishy"

    /// Severity string for `Severity.Valid`
    static var severityValid = "Valid"

    /// Severity string for anything not implemented.
    static var severityNotImplemented = "Not Implemented"

    static var xOT = "OT"
    static var xHT = "HT"
    static var xKorean = "Korean"
    static var xKoreanNon = "Non-Korean"
    static var xEnigmaBerry_0 = "{0} Berry"
    static var xMatches0_1 = "Matches: {0} {1}"
    static var xWurmpleEvo_0 = "Wurmple Evolution: {0}"
    static var xRareFormEvo_0_1 = "Evolves into form: {0} (rare: {1})"

    static var abilityCapsuleUsed = "Ability available with Ability Capsule."
    static var abilityPatchUsed = "Ability available with Ability Patch."
    static var abilityPatchRevertUsed = "Ability available with Ability Patch Revert."
    static var abilityFlag = "Ability matches ability number."
    static var abilityHiddenFail = "Hidden Ability mismatch for encounter type."
    static var abilityHiddenUnavailable = "Hidden Ability not available."
    static var abilityMismatch = "Ability mismatch for encounter."
    static var abilityMismatch3 = "Ability does not match Generation 3 species ability."
    static var abilityMismatchFlag = "Ability does not match ability number."
    static var abilityMismatchGift = "Ability does not match Mystery Gift."
    static var abilityMismatchGrotto = "Hidden Grotto captures should have Hidden Ability."
    static var abilityMismatchHordeSafari = "Hidden Ability on non-horde/friend safari wild encounter."
    static var abilityMismatchPID = "Ability does not match PID."
    static var abilityMismatchSOS = "Hidden Ability on non-SOS wild encounter."
    static var abilityUnexpected = "Ability is not valid for species/form."

    static var awakenedCap = "Individual AV cannot be greater than {0}."
    static var awakenedShouldBeValue = "Individual AV ({1}) should be greater than {0}."

    static var ballAbility = "Can't obtain Hidden Ability with Ball."
    static var ballEggCherish = "Can't have Cherish Ball for regular Egg."
    static var ballEggMaster = "Can't have Master Ball for regular Egg."
    static var ballEnc = "Correct ball for encounter type."
    static var ballEncMismatch = "Can't have ball for encounter type."
    static var ballHeavy = "Can't have Heavy Ball for light, low-catch rate species (Gen VII)."
    static var ballNone = "No check satisfied, assuming illegal."
    static var ballSpecies = "Can't obtain species in Ball."
    static var ballSpeciesPass = "Ball possible for species."
    static var ballUnavailable = "Ball unobtainable in origin Generation."

    static var contestZero = "Contest Stats should be 0."
    static var contestZeroSheen = "Contest Stat Sheen should be 0."
    static var contestSheenTooLow_0 = "Contest Stat Sheen should be >= {0}."
    static var contestSheenTooHigh_0 = "Contest Stat Sheen should be <= {0}."

    static var dateOutsideDistributionWindow = "Met Date is outside of distribution window."

    static var eggContest = "Cannot increase Contest Stats of an Egg."
    static var eggEXP = "Eggs cannot receive experience."
    static var eggFMetLevel_0 = "Invalid Met Level, expected {0}."
    static var eggHatchCycles = "Invalid Egg hatch cycles."
    static var eggLocation = "Able to hatch an Egg at Met Location."
    static var eggLocationInvalid = "Can't hatch an Egg at Met Location."
    static var eggLocationNone = "Invalid Egg Location, expected none."
    static var eggLocationPalPark = "Invalid Met Location, expected Pal Park."
    static var eggLocationTrade = "Able to hatch a traded Egg at Met Location."
    static var eggLocationTradeFail = "Invalid Egg Location, shouldn't be 'traded' while an Egg."
    static var eggMetLocationFail = "Can't obtain Egg from Egg Location."
    static var eggNature = "Eggs cannot have their Stat Nature changed."
    static var eggPokeathlon = "Eggs cannot have Pokéathlon stats."
    static var eggPokerus = "Eggs cannot be infected with Pokérus."
    static var eggPP = "Eggs cannot have modified move PP counts."
    static var eggPPUp = "Cannot apply PP Ups to an Egg."
    static var eggRelearnFlags = "Expected no Relearn Move Flags."
    static var eggShinyLeaf = "Eggs cannot have Shiny Leaf/Crown."
    static var eggShinyPokeStar = "Eggs cannot be a Pokéstar Studios star."
    static var eggSpecies = "Can't obtain Egg for this species."
    static var eggUnhatched = "Valid un-hatched Egg."

    static var encCondition = "Valid Wild Encounter at location."
    static var encConditionBadRNGFrame = "Unable to match encounter conditions to a possible RNG frame."
    static var encConditionBadSpecies = "Species does not exist in origin game."
    static var encConditionBlack = "Valid Wild Encounter at location (Black Flute)."
    static var encConditionBlackLead = "Valid Wild Encounter at location (Black Flute & Pressure/Hustle/Vital Spirit)."
    static var encConditionDexNav = "Valid Wild Encounter at location (DexNav)."
    static var encConditionLead = "Valid Wild Encounter at location (Pressure/Hustle/Vital Spirit)."
    static var encConditionWhite = "Valid Wild Encounter at location (White Flute)."
    static var encConditionWhiteLead = "Valid Wild Encounter at location (White Flute & Pressure/Hustle/Vital Spirit)."

    static var encGift = "Unable to match a gift Egg encounter from origin game."
    static var encGiftEggEvent = "Unable to match an event Egg encounter from origin game."
    static var encGiftIVMismatch = "IVs do not match Mystery Gift Data."
    static var encGiftNicknamed = "Event gift has been nicknamed."
    static var encGiftNotFound = "Unable to match to a Mystery Gift in the database."
    static var encGiftPIDMismatch = "Mystery Gift fixed PID mismatch."
    static var encGiftShinyMismatch = "Mystery Gift shiny mismatch."
    static var encGiftVersionNotDistributed = "Mystery Gift cannot be received by this version."

    static var encInvalid = "Unable to match an encounter from origin game."
    static var encMasteryInitial = "Initial move mastery flags do not match the encounter's expected state."

    static var encTradeChangedNickname = "In-game Trade Nickname has been altered."
    static var encTradeChangedOT = "In-game Trade OT has been altered."
    static var encTradeIndexBad = "In-game Trade invalid index?"
    static var encTradeMatch = "Valid In-game trade."
    static var encTradeUnchanged = "In-game Trade OT and Nickname have not been altered."

    static var encStaticMatch = "Valid gift/static encounter."
    static var encStaticPIDShiny = "Static Encounter shiny mismatch."
    static var encStaticRelearn = "Static encounter relearn move mismatch."

    static var encTypeMatch = "Encounter Type matches encounter."
    static var encTypeMismatch = "Encounter Type does not match encounter."
    static var encUnreleased = "Unreleased event."
    static var encUnreleasedEMewJP = "Non japanese Mew from Faraway Island. Unreleased event."
    static var encUnreleasedHoOArceus = "Arceus from Hall of Origin. Unreleased event."
    static var encUnreleasedPtDarkrai = "Non Platinum Darkrai from Newmoon Island. Unreleased event."
    static var encUnreleasedPtShaymin = "Non Platinum Shaymin from Flower Paradise. Unreleased event."

    static var eReaderAmerica = "American E-Reader Berry in Japanese save file."
    static var eReaderInvalid = "Invalid E-Reader Berry."
    static var eReaderJapan = "Japanese E-Reader Berry in international save file."

    static var effort2Remaining = "2 EVs remaining."
    static var effortAbove252 = "EVs cannot go above 252."
    static var effortAbove510 = "EV total cannot be above 510."
    static var effortAllEqual = "EVs are all equal."
    static var effortCap100 = "Individual EV for a level 100 encounter in Generation 4 cannot be greater than 100."
    static var effortEgg = "Eggs cannot receive EVs."
    static var effortShouldBeZero = "Cannot receive EVs."
    static var effortEXPIncreased = "All EVs are zero, but leveled above Met Level."
    static var effortUntrainedCap = "Individual EV without changing EXP cannot be greater than {0}."

    static var evoInvalid = "Evolution not valid (or level/trade evolution unsatisfied)."
    static var evoTradeReq = "In-game trade {0} should have evolved into {1}."
    static var evoTradeReqOutsider = "Outsider {0} should have evolved into {1}."
    static var evoTradeRequired = "Version Specific evolution requires a trade to opposite version. A Handling Trainer is required."

    static var fateful = "Special In-game Fateful Encounter."
    static var fatefulGiftMissing = "Fateful Encounter with no matching Encounter. Has the Mystery Gift data been contributed?"
    static var fatefulInvalid = "Fateful Encounter should not be checked."
    static var fatefulMissing = "Special In-game Fateful Encounter flag missing."
    static var fatefulMystery = "Mystery Gift Fateful Encounter."
    static var fatefulMysteryMissing = "Mystery Gift Fateful Encounter flag missing."

    static var favoriteMarkingUnavailable = "Favorite Marking is not available."

    static var formArgumentHigh = "Form argument is too high for current form."
    static var formArgumentLow = "Form argument is too low for current form."
    static var formArgumentNotAllowed = "Form argument is not allowed for this encounter."
    static var formArgumentValid = "Form argument is valid."
    static var formArgumentInvalid = "Form argument is not valid."
    static var formBattle = "Form cannot exist outside of a battle."
    static var formEternal = "Valid Eternal Flower encounter."
    static var formEternalInvalid = "Invalid Eternal Flower encounter."
    static var formInvalidGame = "Form cannot be obtained in origin game."
    static var formInvalidNature = "Form cannot have this nature."
    static var formInvalidRange = "Form Count is out of range. Expected <= {0}, got {1}."
    static var formItem = "Held item matches Form."
    static var formItemInvalid = "Held item does not match Form."
    static var formParty = "Form cannot exist outside of Party."
    static var formPikachuCosplay = "Only Cosplay Pikachu can have this form."
    static var formPikachuCosplayInvalid = "Cosplay Pikachu cannot have the default form."
    static var formPikachuEventInvalid = "Event Pikachu cannot have the default form."
    static var formInvalidExpect_0 = "Form is invalid, expected form index {0}."
    static var formValid = "Form is Valid."
    static var formVivillon = "Valid Vivillon pattern."
    static var formVivillonEventPre = "Event Vivillon pattern on pre-evolution."
    static var formVivillonInvalid = "Invalid Vivillon pattern."
    static var formVivillonNonNative = "Non-native Vivillon pattern."

    static var g1CatchRateChain = "Catch rate does not match any species from Pokémon evolution chain."
    static var g1CatchRateEvo = "Catch rate match species without encounters. Expected a preevolution catch rate."
    static var g1CatchRateItem = "Catch rate does not match a valid held item from Generation 2."
    static var g1CatchRateMatchPrevious = "Catch Rate matches a species from Pokémon evolution chain."
    static var g1CatchRateMatchTradeback = "Catch rate matches a valid held item from Generation 2."
    static var g1CatchRateNone = "Catch rate does not match any species from Pokémon evolution chain or any Generation 2 held items."
    static var g1CharNick = "Nickname from Generation 1/2 uses unavailable characters."
    static var g1CharOT = "OT from Generation 1/2 uses unavailable characters."
    static var g1GBEncounter = "Can't obtain Special encounter in Virtual Console games."
    static var g1MoveExclusive = "Generation 1 exclusive move. Incompatible with Non-tradeback moves."
    static var g1MoveLearnSameLevel = "Incompatible moves. Learned at the same level in Red/Blue and Yellow."
    static var g1MoveTradeback = "Non-tradeback Egg move. Incompatible with Generation 1 exclusive moves."
    static var g1OTEvent = "Incorrect RBY event OT Name."
    static var g1OTGender = "Female OT from Generation 1/2 is invalid."
    static var g1Stadium = "Incorrect Stadium OT."
    static var g1StadiumInternational = "Valid International Stadium OT."
    static var g1StadiumJapanese = "Valid Japanese Stadium OT."
    static var g1TradebackPreEvoMove = "Non-tradeback pre evolution move. Incompatible with Generation 1 exclusive moves."
    static var g1Type1Fail = "Invalid Type A, does not match species type."
    static var g1Type2Fail = "Invalid Type B, does not match species type."
    static var g1TypeMatch1 = "Valid Type A, matches species type."
    static var g1TypeMatch2 = "Valid Type B, matches species type."
    static var g1TypeMatchPorygon = "Porygon with valid Type A and B values."
    static var g1TypePorygonFail = "Porygon with invalid Type A and B values. Does not a match a valid type combination."
    static var g1TypePorygonFail1 = "Porygon with invalid Type A value."
    static var g1TypePorygonFail2 = "Porygon with invalid Type B value."
    static var g2InvalidTilePark = "National Park fishing encounter. Unreachable Water tiles."
    static var g2InvalidTileR14 = "Kanto Route 14 fishing encounter. Unreachable Water tiles."
    static var g2InvalidTileSafari = "Generation 2 Safari Zone fishing encounter. Unreachable zone."
    static var g2InvalidTileTreeID = "Found an unreachable tree for Crystal headbutt encounter that matches OTID."
    static var g2InvalidTileTreeNotFound = "Could not find a tree for Crystal headbutt encounter that matches OTID."
    static var g2TreeID = "Found a tree for Crystal headbutt encounter that matches OTID."
    static var g2OTGender = "OT from Virtual Console games other than Crystal cannot be female."

    static var g3EReader = "Non Japanese Shadow E-reader Pokémon. Unreleased encounter."
    static var g3OTGender = "OT from Colosseum/XD cannot be female."
    static var g4InvalidTileR45Surf = "Johto Route 45 surfing encounter. Unreachable Water tiles."
    static var g5ID_N = "The Name/TID16/SID16 of N is incorrect."
    static var g5IVAll30 = "All IVs of N's Pokémon should be 30."
    static var g5OTGenderN = "N's Pokémon must have a male OT gender."
    static var g5PIDShinyGrotto = "Hidden Grotto captures cannot be shiny."
    static var g5PIDShinyN = "N's Pokémon cannot be shiny."
    static var g5SparkleInvalid = "Special In-game N's Sparkle flag should not be checked."
    static var g5SparkleRequired = "Special In-game N's Sparkle flag missing."

    static var ganbaruStatTooHigh = "One or more Ganbaru Value is above the natural limit of (10 - IV bonus)."

    static var genderInvalidNone = "Genderless Pokémon should not have a gender."
    static var geoBadOrder = "GeoLocation Memory: Gap/Blank present."
    static var geoHardwareInvalid = "Geolocation: Country is not in 3DS region."
    static var geoHardwareRange = "Invalid Console Region."
    static var geoHardwareValid = "Geolocation: Country is in 3DS region."
    static var geoMemoryMissing = "GeoLocation Memory: Memories should be present."
    static var geoNoCountryHT = "GeoLocation Memory: HT Name present but has no previous Country."
    static var geoNoRegion = "GeoLocation Memory: Region without Country."

    static var hyperTooLow_0 = "Can't Hyper Train a Pokémon that isn't level {0}."
    static var hyperPerfectAll = "Can't Hyper Train a Pokémon with perfect IVs."
    static var hyperPerfectOne = "Can't Hyper Train a perfect IV."
    static var hyperPerfectUnavailable = "Can't Hyper Train any IV(s)."

    static var itemEgg = "Eggs cannot hold items."
    static var itemUnreleased = "Held item is unreleased."

    static var iVAllEqual_0 = "All IVs are {0}."
    static var iVNotCorrect = "IVs do not match encounter requirements."
    static var iVF_COUNT0_31 = "Should have at least {0} IVs = 31."

    static var levelEXPThreshold = "Current experience matches level threshold."
    static var levelEXPTooHigh = "Current experience exceeds maximum amount for level 100."
    static var levelMetBelow = "Current level is below met level."
    static var levelMetGift = "Met Level does not match Mystery Gift level."
    static var levelMetGiftFail = "Current Level below Mystery Gift level."
    static var levelMetSane = "Current level is not below met level."

    static var markValueOutOfRange_0 = "Individual marking at index {0} is not within the allowed value range."
    static var markValueShouldBeZero = "Marking flags cannot be set."
    static var markValueUnusedBitsPresent = "Marking flags uses bits beyond the accessible range."

    static var memoryArgBadCatch = "{0} Memory: {0} did not catch this."
    static var memoryArgBadHatch = "{0} Memory: {0} did not hatch this."
    static var memoryArgBadHT = "Memory: Can't have Handling Trainer Memory as Egg."
    static var memoryArgBadID = "{0} Memory: Can't obtain Memory on {0} Version."
    static var memoryArgBadItem = "{0} Memory: Species can't hold this item."
    static var memoryArgBadLocation = "{0} Memory: Can't obtain Location on {0} Version."
    static var memoryArgBadMove = "{0} Memory: Species can't learn this move."
    static var memoryArgBadOTEgg = "{0} Memory: Link Trade is not a valid first memory."
    static var memoryArgBadSpecies = "{0} Memory: Can't capture species in game."
    static var memoryArgSpecies = "{0} Memory: Species can be captured in game."
    static var memoryCleared = "Memory: Not cleared properly."
    static var memoryF_0_Valid = "{0} Memory is valid."
    static var memoryFeelInvalid = "{0} Memory: Invalid Feeling."
    static var memoryHTFlagInvalid = "Untraded: Current handler should not be the Handling Trainer."
    static var memoryHTGender = "HT Gender invalid: {0}"
    static var memoryHTLanguage = "HT Language is missing."

    static var memoryIndexArgHT = "Should have a HT Memory TextVar value (somewhere)."
    static var memoryIndexFeel = "{0} Memory: Feeling should be index {1}."
    static var memoryIndexFeelHT09 = "Should have a HT Memory Feeling value 0-9."
    static var memoryIndexID = "{0} Memory: Should be index {1}."
    static var memoryIndexIntensity = "{0} Memory: Intensity should be index {1}."
    static var memoryIndexIntensityHT1 = "Should have a HT Memory Intensity value (1st)."
    static var memoryIndexIntensityMin = "{0} Memory: Intensity should be at least {1}."
    static var memoryIndexLinkHT = "Should have a Link Trade HT Memory."
    static var memoryIndexVar = "{0} Memory: TextVar should be index {1}."
    static var memoryMissingHT = "Memory: Handling Trainer Memory missing."
    static var memoryMissingOT = "Memory: Original Trainer Memory missing."

    static var memorySocialZero = "Social Stat should be zero."
    static var memorySocialTooHigh_0 = "Social Stat should be <= {0}"

    static var memoryStatAffectionHT0 = "Untraded: Handling Trainer Affection should be 0."
    static var memoryStatAffectionOT0 = "OT Affection should be 0."
    static var memoryStatFriendshipHT0 = "Untraded: Handling Trainer Friendship should be 0."
    static var memoryStatFriendshipOTBaseEvent = "Event OT Friendship does not match base friendship."

    static var metDetailTimeOfDay = "Met Time of Day value is not within the expected range."

    static var memoryStatFullness = "Fullness should be {0}."
    static var memoryStatEnjoyment = "Enjoyment should be {0}."

    static var moveEggFIncompatible0_1 = "{0} Inherited Move. Incompatible with {1} inherited moves."
    static var moveEggIncompatible = "Egg Move. Incompatible with event Egg moves."
    static var moveEggIncompatibleEvent = "Event Egg Move. Incompatible with normal Egg moves."
    static var moveEggInherited = "Inherited Egg move."
    static var moveEggInheritedTutor = "Inherited tutor move."
    static var moveEggInvalid = "Not an expected Egg move."
    static var moveEggInvalidEvent = "Egg Move. Not expected in an event Egg."
    static var moveEggInvalidEventLevelUp = "Inherited move learned by Level-up. Not expected in an event Egg."
    static var moveEggInvalidEventLevelUpGift = "Inherited move learned by Level-up. Not expected in a gift Egg."
    static var moveEggInvalidEventTMHM = "Inherited TM/HM move. Not expected in an event Egg."
    static var moveEggInvalidEventTutor = "Inherited tutor move. Not expected in an event Egg."
    static var moveEggLevelUp = "Inherited move learned by Level-up."
    static var moveEggMissing = "Event Egg move missing."
    static var moveEggMoveGift = "Egg Move. Not expected in a gift Egg."
    static var moveEggTMHM = "Inherited TM/HM move."

    static var moveEventEggLevelUp = "Inherited move learned by Level-up. Incompatible with event Egg moves."
    static var moveEvoFCombination_0 = "Moves combinations is not compatible with {0} evolution."
    static var moveEvoFHigher = "Incompatible evolution moves. {1} Move learned at a higher level than other {0} moves."
    static var moveEvoFLower = "Incompatible evolution moves. {0} Move learned at a lower level than other {1} moves."
    static var moveFDefault_0 = "Default move in Generation {0}."
    static var moveFExpect_0 = "Expected the following Moves: {0}"
    static var moveFExpectSingle_0 = "Expected: {0}"
    static var moveFLevelUp_0 = "Learned by Level-up in Generation {0}."
    static var moveFTMHM_0 = "Learned by TM/HM in Generation {0}."
    static var moveFTutor_0 = "Learned by Move Tutor in Generation {0}."
    static var moveKeldeoMismatch = "Keldeo Move/Form mismatch."
    static var moveNincada = "Only one Ninjask move allowed."
    static var moveNincadaEvo = "Learned by evolving Nincada into Ninjask."
    static var moveNincadaEvoF_0 = "Learned by evolving Nincada into Ninjask in Generation {0}."
    static var movePPTooHigh_0 = "Move {0} PP is above the amount allowed."
    static var movePPUpsTooHigh_0 = "Move {0} PP Ups is above the amount allowed."
    static var moveSourceShared = "Shared Non-Relearn Move."
    static var moveSourceSharedF = "Shared Non-Relearn Move in Generation {0}."

    static var moveRelearnDexNav = "Not an expected DexNav move."
    static var moveRelearnUnderground = "Not an expected Underground egg move."
    static var moveRelearnEgg = "Base Egg move."
    static var moveRelearnEggMissing = "Base Egg move missing."
    static var moveRelearnFExpect_0 = "Expected the following Relearn Moves: {0} ({1})"
    static var moveRelearnFMiss_0 = "Relearn Moves missing: {0}"
    static var moveRelearnInvalid = "Not an expected Relearnable move."
    static var moveRelearnNone = "Expected no Relearn Move in slot."

    static var moveShopAlphaMoveShouldBeMastered = "Alpha Move should be marked as mastered."
    static var moveShopAlphaMoveShouldBeOther = "Alpha encounter cannot be found with this Alpha Move."
    static var moveShopAlphaMoveShouldBeZero = "Only Alphas may have an Alpha Move set."
    static var moveShopMasterInvalid_0 = "Cannot manually master {0}: not permitted to master."
    static var moveShopMasterNotLearned_0 = "Cannot manually master {0}: not in possible learned level up moves."
    static var moveShopPurchaseInvalid_0 = "Cannot purchase {0} from the move shop."

    static var moveSourceDefault = "Default move."
    static var moveSourceDuplicate = "Duplicate Move."
    static var moveSourceEgg = "Egg Move."
    static var moveSourceEggEvent = "Event Egg Move."
    static var moveSourceEmpty = "Empty Move."
    static var moveSourceInvalid = "Invalid Move."
    static var moveSourceInvalidSketch = "Invalid Move (Sketch)."
    static var moveSourceLevelUp = "Learned by Level-up."
    static var moveSourceRelearn = "Relearnable Move."
    static var moveSourceSpecial = "Special Non-Relearn Move."
    static var moveSourceTMHM = "Learned by TM/HM."
    static var moveSourceTutor = "Learned by Move Tutor."
    static var moveSourceTR = "Unexpected Technical Record Learned flag: {0}"

    static var nickFlagEggNo = "Egg must be not nicknamed."
    static var nickFlagEggYes = "Egg must be nicknamed."
    static var nickInvalidChar = "Cannot be given this Nickname."
    static var nickLengthLong = "Nickname too long."
    static var nickLengthShort = "Nickname is empty."
    static var nickMatchLanguage = "Nickname matches species name."
    static var nickMatchLanguageEgg = "Egg matches language Egg name."
    static var nickMatchLanguageEggFail = "Egg name does not match language Egg name."
    static var nickMatchLanguageFail = "Nickname does not match species name."
    static var nickMatchLanguageFlag = "Nickname flagged, matches species name."
    static var nickMatchNoOthers = "Nickname does not match another species name."
    static var nickMatchNoOthersFail = "Nickname matches another species name (+language)."

    static var otLanguage = "Language ID should be {0}, not {1}."
    static var otLong = "OT Name too long."
    static var otShort = "OT Name too short."
    static var otSuspicious = "Suspicious Original Trainer details."

    static var ot_IDEqual = "TID16 and SID16 are equal."
    static var ot_IDs0 = "TID16 and SID16 are 0."
    static var ot_SID0 = "SID16 is zero."
    static var ot_SID0Invalid = "SID16 should be 0."
    static var ot_TID0 = "TID16 is zero."
    static var ot_IDInvalid = "TID16 and SID16 combination is not possible."

    static var pidEncryptWurmple = "Wurmple evolution Encryption Constant mismatch."
    static var pidEncryptZero = "Encryption Constant is not set."
    static var pidEqualsEC = "Encryption Constant matches PID."
    static var pidGenderMatch = "Gender matches PID."
    static var pidGenderMismatch = "PID-Gender mismatch."
    static var pidNatureMatch = "Nature matches PID."
    static var pidNatureMismatch = "PID-Nature mismatch."
    static var pidTypeMismatch = "PID+ correlation does not match what was expected for the Encounter's type."
    static var pidZero = "PID is not set."

    static var pokerusDaysTooHigh_0 = "Pokérus Days Remaining value is too high; expected <= {0}."
    static var pokerusStrainUnobtainable_0 = "Pokérus Strain {0} cannot be obtained."

    static var ribbonAllValid = "All ribbons accounted for."
    static var ribbonEgg = "Can't receive Ribbon(s) as an Egg."
    static var ribbonFInvalid_0 = "Invalid Ribbons: "
    static var ribbonFMissing_0 = "Missing Ribbons: "
    static var ribbonMarkingFInvalid_0 = "Invalid Marking: {0}"
    static var ribbonMarkingAffixedF_0 = "Invalid Affixed Ribbon/Marking: {0}"

    static var statDynamaxInvalid = "Dynamax Level is not within the expected range."
    static var statIncorrectHeight = "Calculated Height does not match stored value."
    static var statIncorrectHeightCopy = "Copy Height does not match the original value."
    static var statIncorrectHeightValue = "Height does not match the expected value."
    static var statIncorrectWeight = "Calculated Weight does not match stored value."
    static var statIncorrectWeightValue = "Weight does not match the expected value."
    static var statInvalidHeightWeight = "Height / Weight values are statistically improbable."
    static var statIncorrectCP = "Calculated CP does not match stored value."
    static var statGigantamaxInvalid = "Gigantamax Flag mismatch."
    static var statGigantamaxValid = "Gigantamax Flag was changed via Max Soup."
    static var statNatureInvalid = "Stat Nature is not within the expected range."
    static var statBattleVersionInvalid = "Battle Version is not within the expected range."
    static var statNobleInvalid = "Noble Flag mismatch."
    static var statAlphaInvalid = "Alpha Flag mismatch."

    static var superComplete = "Super Training complete flag mismatch."
    static var superDistro = "Distribution Super Training missions are not released."
    static var superEgg = "Can't Super Train an Egg."
    static var superNoComplete = "Can't have active Super Training complete flag for origins."
    static var superNoUnlocked = "Can't have active Super Training unlocked flag for origins."
    static var superUnavailable = "Super Training missions are not available in games visited."
    static var superUnused = "Unused Super Training Flag is flagged."

    static var teraTypeIncorrect = "Tera Type does not match the expected value."
    static var teraTypeMismatch = "Tera Type does not match either of the default types."

    static var tradeNotAvailable = "Encounter cannot be traded to the active trainer."

    static var transferBad = "Incorrectly transferred from previous generation."

    static var transferCurrentHandlerInvalid = "Invalid Current handler value, trainer details for save file expected another value."
    static var transferEgg = "Can't transfer Eggs between Generations."
    static var transferEggLocationTransporter = "Invalid Met Location, expected Poké Transfer."
    static var transferEggMetLevel = "Invalid Met Level for transfer."
    static var transferFlagIllegal = "Flagged as illegal by the game (glitch abuse)."
    static var transferHTFlagRequired = "Current handler cannot be past gen OT for transferred specimen."
    static var transferHTMismatchName = "Handling trainer does not match the expected trainer name."
    static var transferHTMismatchLanguage = "Handling trainer does not match the expected trainer language."
    static var transferMet = "Invalid Met Location, expected Poké Transfer or Crown."
    static var transferNotPossible = "Unable to transfer into current format from origin format."
    static var transferMetLocation = "Invalid Transfer Met Location."
    static var transferMove = "Incompatible transfer move."
    static var transferMoveG4HM = "Defog and Whirlpool. One of the two moves should have been removed before transferred to Generation 5."
    static var transferMoveHM = "Generation {0} HM. Should have been removed before transferred to Generation {1}."
    static var transferNature = "Invalid Nature for transfer Experience."
    static var transferObedienceLevel = "Invalid Obedience Level."
    static var transferOriginFInvalid0_1 = "{0} origin cannot exist in the currently loaded ({1}) save file."
    static var transferPIDECBitFlip = "PID should be equal to EC [with top bit flipped]!"
    static var transferPIDECEquals = "PID should be equal to EC!"
    static var transferPIDECXor = "Encryption Constant matches shinyxored PID."
    static var transferTrackerMissing = "Pokémon HOME Transfer Tracker is missing."
    static var transferTrackerShouldBeZero = "Pokémon HOME Transfer Tracker should be 0."
}
